#!/usr/bin/env bash

MYSQL_CMD="mysql --defaults-file=~/.my.cnf.relevant log"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql"
TSV_DIR="$REMOTEUSERHOME/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"

cd $CHECKOUT_DIR
echo "Pulling latest changes from repository..."
git pull > /dev/null
echo "Generating SQL files..."
python $CHECKOUT_DIR/generate.py $SQL_DIR

for sqlpath in `ls $SQL_DIR/perf/*-filerepoinfo.sql`; do
        wikiname=`basename $sqlpath | sed "s/-filerepoinfo.sql//"`
        echo "Updating perf data for $wikiname wiki..."

        for sqlfilepath in `ls $SQL_DIR/perf/${wikiname}-*.sql`; do
                statname=`basename $sqlfilepath | sed "s/.*-//" | sed "s/.sql//"`
                echo "  $statname..."
                tsvpath=$TSV_DIR/mvp_$wikiname-$statname.tsv
                $MYSQL_CMD < $sqlfilepath > $tsvpath
                mv -f $tsvpath $PUBLIC_DIR/media-viewer-perf-$wikiname-$statname.tsv
        done
        echo "  Done!"
done

echo "Updating mmv-versus-filepage perf data..."
tsvpath="$TSV_DIR/mvp_mmv_versus_filepage.tsv"
$MYSQL_CMD < $CHECKOUT_DIR/perf/mmv-versus-filepage.sql > $tsvpath && mv -f $tsvpath $PUBLIC_DIR/media-viewer-perf-mmv-versus-filepage.tsv
echo "  Done!"