#!/usr/bin/env bash

REMOTEUSER="marktraceur"
MYSQL_CMD="mysql --defaults-file=~/.my.cnf.relevant log"
SQL_DIR="/home/$REMOTEUSER/multimedia/geoperf"
TSV_DIR="/home/$REMOTEUSER/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"

for sqlpath in `ls $SQL_DIR/*-image.sql | grep -v template.sql`; do
        wikiname=`basename $sqlpath | sed "s/-image.sql//"`
        echo "Updating geo perf data for $wikiname wiki..."

        for sqlfilepath in `ls $SQL_DIR/${wikiname}-*.sql`; do
                statname=`basename $sqlfilepath | sed "s/.*-//" | sed "s/.sql//"`
                echo "  $statname..."
                tsvpath=$TSV_DIR/mvp_$wikiname-$statname.tsv
                $MYSQL_CMD < $sqlfilepath > $tsvpath
                mv -f $tsvpath $PUBLIC_DIR/media-viewer-geoperf-$wikiname-$statname.tsv
        done
        echo "  Done!"
done
