#!/usr/bin/env bash

if [[ -z "$REMOTEUSERHOME" ]]
then
	echo "You must define the REMOTEUSERHOME environment variable before calling this script"
	exit 1
fi

MYSQL_CMD="mysql --defaults-file=~/.my.cnf.relevant log"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql"
TSV_DIR="$REMOTEUSERHOME/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

$CHECKOUT_DIR/deploy

for sqlpath in `ls $SQL_DIR/duration/*.sql`; do
	wikiname=`basename $sqlpath | sed "s/.sql//"`
	echo "Updating loading durations for $wikiname wiki..."
	tsvpath=$TSV_DIR/mvd_$wikiname.tsv
	$MYSQL_CMD < $sqlpath > $tsvpath
	mv -f $tsvpath $PUBLIC_DIR/media-viewer-duration-$wikiname.tsv
done
