#!/usr/bin/env bash

if [[ -z "$REMOTEUSERHOME" ]]
then
	echo "You must define the REMOTEUSERHOME environment variable before calling this script"
	exit 1
fi

MYSQL_CMD="mysql --defaults-file=~/.my.cnf.relevant"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql/optout"
TSV_DIR="$REMOTEUSERHOME/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

if [ ! -d "$SQL_DIR" ]
then
	mkdir "$SQL_DIR"
fi

cp "$CHECKOUT_DIR/optout/global.sql" "$SQL_DIR"

$CHECKOUT_DIR/deploy

for sqlpath in `ls $SQL_DIR/*.sql`; do
	wikiname=`basename $sqlpath | sed "s/.sql//"`

	# we skip global.sql because it needs to run last
	[ "$wikiname" == "global" ] && continue

	echo "Updating optout counts for $wikiname wiki..."
	tsvpath=$TSV_DIR/mvo_$wikiname.tsv
	$MYSQL_CMD $wikiname < $sqlpath > $tsvpath
	mv -f $tsvpath $PUBLIC_DIR/media-viewer-optout-$wikiname.tsv
	chmod 664 $PUBLIC_DIR/media-viewer-optout-$wikiname.tsv
done

# global needs to run last, because it's reading the data for all wikis from the staging table

echo "Updating optout counts for global wiki..."
tsvpath=$TSV_DIR/mvo_global.tsv
$MYSQL_CMD log < "$REMOTEUSERHOME/tsvs_sql/optout/global.sql" > $tsvpath
mv -f $tsvpath $PUBLIC_DIR/media-viewer-optout-global.tsv
chmod 664 $PUBLIC_DIR/media-viewer-optout-global.tsv
