#!/usr/bin/env bash

if [[ -z "$REMOTEUSERHOME" ]]
then
	echo "You must define the REMOTEUSERHOME environment variable before calling this script"
	exit 1
fi

MYSQL_CMD="mysql --defaults-extra-file=/etc/mysql/conf.d/research-client.cnf -hanalytics-store.eqiad.wmnet log"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql/perf"
TSV_DIR="$REMOTEUSERHOME/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

if [ ! -d "$SQL_DIR" ]
then
	mkdir "$SQL_DIR"
fi

$CHECKOUT_DIR/deploy

for sqlpath in `ls $SQL_DIR/*-filerepoinfo.sql`; do
	wikiname=`basename $sqlpath | sed "s/-filerepoinfo.sql//"`
	echo "Updating perf data for $wikiname wiki..."

	for sqlfilepath in `ls $SQL_DIR/${wikiname}-*.sql`; do
		statname=`basename $sqlfilepath | sed "s/.*-//" | sed "s/.sql//"`
		echo "  $statname..."
		tsvpath=$TSV_DIR/mvp_$wikiname-$statname.tsv
		$MYSQL_CMD < $sqlfilepath > $tsvpath
		mv -f $tsvpath $PUBLIC_DIR/media-viewer-perf-$wikiname-$statname.tsv
		chmod 664 $PUBLIC_DIR/media-viewer-perf-$wikiname-$statname.tsv
	done
	echo "  Done!"
done

echo "Updating cache miss ratio data..."
tsvpath="$TSV_DIR/cache-miss-ratio.tsv"
$MYSQL_CMD < $CHECKOUT_DIR/perf/cache-miss-ratio.sql > $tsvpath && mv -f $tsvpath $PUBLIC_DIR/media-viewer-cache-miss-ratio.tsv
chmod 664 $PUBLIC_DIR/media-viewer-cache-miss-ratio.tsv

echo "Updating mmv-versus-filepage perf data..."
tsvpath="$TSV_DIR/mvp_mmv_versus_filepage.tsv"
$MYSQL_CMD < $CHECKOUT_DIR/perf/mmv-versus-filepage.sql > $tsvpath && mv -f $tsvpath $PUBLIC_DIR/media-viewer-perf-mmv-versus-filepage.tsv
chmod 664 $PUBLIC_DIR/media-viewer-perf-mmv-versus-filepage.tsv
echo "  Done!"

echo "Updating perf by upload time data..."
tsvpath="$TSV_DIR/perf-by-upload-time.tsv"
$MYSQL_CMD < $CHECKOUT_DIR/perf/perf-by-upload-time.sql > $tsvpath && mv -f $tsvpath $PUBLIC_DIR/media-viewer-perf-by-upload-time.tsv
chmod 664 $PUBLIC_DIR/media-viewer-perf-by-upload-time.tsv
