#!/usr/bin/env bash

if [[ -z "$REMOTEUSERHOME" ]]
then
	echo "You must define the REMOTEUSERHOME environment variable before calling this script"
	exit 1
fi

MYSQL_CMD="mysql --defaults-file=~/.my.cnf.relevant log"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql/uw-funnel"
TSV_DIR="$REMOTEUSERHOME/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

sqlfilepath="$CHECKOUT_DIR/uw-funnel/relative.sql"
tsvpath=$TSV_DIR/uw-funnel-relative.tsv
echo "Updating UploadWizard relative funnel data..."

$MYSQL_CMD < $sqlfilepath > $tsvpath
mv -f $tsvpath $PUBLIC_DIR/upload-wizard-funnel-relative.tsv
chmod 664 $PUBLIC_DIR/upload-wizard-funnel-relative.tsv

sqlfilepath="$CHECKOUT_DIR/uw-funnel/absolute.sql"
tsvpath=$TSV_DIR/uw-funnel-absolute.tsv
echo "Updating UploadWizard absolute funnel data..."

$MYSQL_CMD < $sqlfilepath > $tsvpath
mv -f $tsvpath $PUBLIC_DIR/upload-wizard-funnel-absolute.tsv
chmod 664 $PUBLIC_DIR/upload-wizard-funnel-absolute.tsv

sqlfilepath="$CHECKOUT_DIR/uw-funnel/overview.sql"
tsvpath=$TSV_DIR/uw-funnel-overview.tsv
echo "Updating UploadWizard funnel overview data..."

# limn can't handle headers; survival rate is meaningless for the last step
$MYSQL_CMD < $sqlfilepath | tail -n+2 | head -n-1 > $tsvpath
mv -f $tsvpath $PUBLIC_DIR/upload-wizard-funnel-overview.tsv
chmod 664 $PUBLIC_DIR/upload-wizard-funnel-overview.tsv

echo "  Done!"
