#!/usr/bin/env bash

if [[ -z "$REMOTEUSERHOME" ]]
then
	echo "You must define the REMOTEUSERHOME environment variable before calling this script"
	exit 1
fi

MYSQL_CMD="mysql --defaults-file=~/.my.cnf.relevant log"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql/uw-funnel"
TSV_DIR="$REMOTEUSERHOME/tsvs_new"
PUBLIC_DIR="/a/public-datasets/all/multimedia"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

sqlfilepath="$CHECKOUT_DIR/uw-funnel/query.sql"
tsvpath=$TSV_DIR/uw-funnel.tsv
echo "Updating UploadWizard funnel data..."

$MYSQL_CMD < $sqlfilepath > $tsvpath

mv -f $tsvpath $PUBLIC_DIR/upload-wizard-funnel.tsv
echo "  Done!"
