#!/usr/bin/env bash

REMOTEUSERHOME="/home/marktraceur"
SQL_DIR="$REMOTEUSERHOME/tsvs_sql"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

cd $CHECKOUT_DIR
echo "Pulling latest changes from repository..."
git pull > /dev/null
echo "Generating SQL files..."
python $CHECKOUT_DIR/generate.py $SQL_DIR
