#!/usr/bin/env bash

if [[ -z "$REMOTEUSERHOME" ]]
then
	echo "You must define the REMOTEUSERHOME environment variable before calling this script"
	exit 1
fi

SQL_DIR="$REMOTEUSERHOME/tsvs_sql"
CHECKOUT_DIR="$REMOTEUSERHOME/multimedia"

cd $CHECKOUT_DIR
echo "Pulling latest changes from repository..."
git pull > /dev/null
echo "Generating SQL files..."
python $CHECKOUT_DIR/generate.py $SQL_DIR
